const express = require('express');
const transactionRouter = express.Router();
const transactionController = require('../controller/transaction.controller');
transactionRouter.get('/getproducts', transactionController.loadProducts);
transactionRouter.get('/getallproducts', transactionController.loadAllProducts);
transactionRouter.get('/getsuppliers', transactionController.loadSuppliers);
transactionRouter.get('/getcustomers', transactionController.loadCustomers);
transactionRouter.post('/createstockin', transactionController.createStockIn);
transactionRouter.delete('/delete/:id', transactionController.deleteTransaction);
transactionRouter.post('/update/:id', transactionController.updateTransaction);
transactionRouter.post('/createstockout', transactionController.createStockOut);
transactionRouter.post('/updatestockout/:id', transactionController.updateTransactionStockOut);
transactionRouter.post('/producttimeline', transactionController.productTimeline);
module.exports = transactionRouter;